### PR TITLE
[472221] Update the distribution management channels

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472221

**Comment by jponge** [comment]
This is a work in progress.

I've tested uploading to BinTray a release that wasn't published: it works great.

I haven't tested uploading the snapshots to repo.eclipse.org: this shall be done from a Hudson instance.

**Comment by jponge** [comment]
@danielpetisme this would need to be merged, can you please review it from a CI PoV?

**Comment by jponge** [comment]
The latest change references repo.eclipse.org by default on snapshots and releases, which should be great for CI at Eclipse.

Manually releasing to Bintray works using the `bintray` profile.

**Comment by jponge** [comment]
Good to merge for me.

Additional reviews welcome, or I'll just merge later this evening.

**Pull request merged**
