### PR TITLE
FIX #513: issue with implicit upcast of primitive

### LINKED ISSUE #513: this simple program does not work
```golo
module teste.WebServer

import java.lang
import java.net.InetSocketAddress
import com.sun.net.httpserver.HttpServer

function main = |args| {

  let server = HttpServer.create(InetSocketAddress("localhost", 8081), 0)
	let handler1 = |exchange| {
    let response = "bem vindo"
    exchange: getResponseHeaders(): set("Content-Type", "text/plain")
		println(response: length())
    exchange: sendResponseHeaders(200, response: length())
    exchange: getResponseBody(): write(response: getBytes())
    exchange: close()
  }
  server: createContext("/", handler1)
	let handler2 = |exchange| {
	 let response = "tchau"
    exchange: getResponseHeaders(): set("Content-Type", "text/plain")
    exchange: sendResponseHeaders(200, response: length())
    exchange: getResponseBody(): write(response: getBytes())
    exchange: close()
    server: stop(5)
  }
  server: createContext("/shut", handler2)
  
  server: start()
  println("> http://localhost:8081/")
}
```

### PR DESCRIPTION
**Pull request by yloiseau**
When java method expect e.g. a float and it is called with a int, the
method is not found (since the big method resolution refactoring).

- adds a substituability comparison for method params
- use Extractors in function call resolution

### CODE REVIEW

**Comment by jponge** [comment]
Nice, the following now works!

```golo
module Yo

function main = |args| {
  println("Sleep...")
  Thread.sleep(3000)
  println("Done")
}
```

**Comment by jponge** [comment]
Works on methods, too:

```golo
module Yo

import java.util.Random

function main = |args| {
  let rand = Random()
  let stream = rand: longs(100)
  println(stream: filter(|n| -> n % 2 == 0): count())
}
```

**Comment by jponge** [comment]
@yloiseau It's the method handle chain doing the upcast, right?

**Comment by yloiseau** [comment]
@jponge the issue was that the method was not found, so I changed the lookup. The cast itself is done as usual by adapting the method handle.

**Comment by jponge** [comment]
Ah I missed the adaptation, can you point me to it?

**Comment by yloiseau** [comment]
By adaptation I just mean `handle.asType`...

**Comment by jponge** [comment]
Ok so it's in the MH chain :-)

**Comment by Artpej** [comment]
:+1:

**Pull request merged**
