### PR TITLE
Compile Java sources with the -parameters flag

### PR DESCRIPTION
**Pull request by jponge**
Fix for #351

### CODE REVIEW

**Comment by jponge** [comment]
Surprisingly it fails the build :tada: 

In `namedarguments-anoncall.golo`, it seems like `invoke` calls on function references want `this` to be taken as a named parameter.

Any idea @yloiseau?

**Comment by danielpetisme** [comment]
If you look in `FunctionCallSupport.reorderArguments` a mismatch appears.
* `Method`: `FunctionReference.invoke`
* `parameters`: `args`
* `arguments`: `this, before, after`

The `reorderArguments method` has a sanity check to be sure the argument names match parameter names. 
Obviously, this check doesn't find the argument `this` in the parameter names list {args}. You will get the same error with the `before` argument.

The weird thing is why it resolve to the `invoke` method and not the `$$_closure_XX` method...

**Comment by yloiseau** [comment]
This change only imply changes in the way _Java_ methods are called. I think that is why only this `invoke` fails, since we are calling the `FunctionReference::invoke` method. However, this method is a generic varargs one, with `Object... args` as signature. These tests were added in the fix of #335 (PR #346), whose only significant change was to check argument names in `ParseTreeToGoloIrVisitor::visit(ASTAnonymousFunctionInvocation node, Object data)`.

This errors only shows that the test is buggy (shame on me). I only checked that named arguments are possible (the issue raised by @k33g showed that it was not even valid), but not that they are properly reordered. Indeed, if you try to switch named arguments (say `yo("sam"): invoke(after="!", before="Hello")`) the test fails (even in master branch) so the bug is not actually fixed in the `invoke` case (others seems to be OK). Since the `invoke` is generic, I'm not even sure it could be possible. And now that the names are checked due to the `-paramerters` flag, the issue becomes visible.

**Comment by yloiseau** [comment]
I think we should simply discard the validity of calling `invoke` with named arguments, and remove the test. After all, `invoke` is a generic way to dynamically call _any_ function reference. 

If we want to deal with named arguments here, the runtime has to check the method handle of the receiving reference, instead of the `invoke` one, and then do a special case in `MethodFinder::toMethodHandle`.

**Comment by danielpetisme** [comment]
I tried the following test :
`"JavaScript": substring(endIndex = 4, beginIndex = 0)`
it doesn't work, the reordering is not applied (`endIndex = 0, beginIndex = 4`) works. The Java method resolution relies only on the method signature and doesn't reorder args.

The aparently harmless `-parameters` flag raise a question. Should named argument work with Java or not?

**Comment by yloiseau** [comment]
(@danielpetisme did you delete your previous comment?)
Damn... I thought it would work for fixed arity methods, but indeed, since we probably bypass the java mechanism in the invoke dynamic, it should not be surprising. Time for yet another refactoring of `MethodInvocationSupport` and `RegularMethodFinder` :angry: 

I think we should at least try to make it work for java fixed-arity functions, at least for consistency.

**Comment by danielpetisme** [comment]
@yloiseau yes I deleted it because my test was not meaningfull.
I tried to use named args with a JDK class and since the JDK is not compiled with the `-parameters` flag it just can't work.

I made a test with a the Java `Predefined` class and it works `range(to = 'd', from = 'a')`.

I think we should raise a warning or exception when the dev uses named args with Java classes not compiled with `-parameters`.

**Comment by yloiseau** [comment]
Ok. In that case, my remark is not meaningful either. Your tests made a point however, by highlighting the issue. Moreover, this issue will also raise when using 3rd party libs not compiled with `-parameters`. I had not envisioned this point. Too bad for consistency. 

:+1: for the warning.

**Comment by yloiseau** [comment]
Does any other JVM language have named arguments? And if so, how do they deal with the native java aspect?

**Comment by jponge** [comment]
Yeah, the JDK itself is not compiled with the flag, it's... bad https://julien.ponge.org/blog/java8-parameter-names-and-jdk-dogfooding/

**Comment by danielpetisme** [comment]
to sum up,
1- the following snippet from `namedarguments-anoncall.golo` can't work
````
  assertEquals(yo("sam"): invoke(before="Hello", after="!"), expected)
  assertEquals(
    ^say: bindAt("message", "sam"): invoke(before="Hello", after="!"),
    expected)

  assertEquals(^add: invoke(left="a", right="b"), "ab")
  assertEquals((|left, right| -> left + right): invoke(left="a", right="b"), "ab")
````
because the true signature of `invoke` is `invoke(Object... args)` (no mention of `before`, `after`, `left` or `right`

So to fix the issue, we can't simply remove this tests

2- we have a bug when `invoke` is used in the proper way `invoke(args= ["Hello", "!"])`, it fails because it has a argument `this` not defined in the method formal parameters list.
We should create another issue to track it

3- Create an issue to discuss how manage properly named args with not incompatible Java classes (ie. not compiled with the `-parameters` flag.

**Pull request merged**
