### PR TITLE
Add method toDynamicObjectTree

### PR DESCRIPTION
**Pull request by k33g**
Hey 👋 @yloiseau @jponge ... and the others (btw, it would be nice to use the team feature of :octocat: ➡️ simpler to notifiy everybody) what do you think about this ⬇️ 

What I would like to implement:  add a `toDynamicObjectTree` to the JSON module

`toDynamicObjectTree` returns a new dynamic object (or an array of dynamic objects) from a JSON string where each level entry is mapped into the dynamic object or an array of dynamic objects.

``` golo
let obj = JSON.toDynamicObject("""
  {
    "id":"bob",
    "friends":[
      {"name":"sam"}, {"name":"jane"}, {"name":"john"}
    ],
    "address": {
      "street":"88 Colin P Kelly Jr St",
      "city":"San Francisco",
      "zip":"CA 94107",
      "country":"United States"
    }
  }
""")

obj: friends(): get(2): name(): equals("john") # true
obj: address(): city(): equals("San Francisco") # true
```

### CODE REVIEW

**Comment by jponge** [comment]
Shifting review to 3.2.0-M6

**Comment by k33g** [comment]
@jponge ok, but about the feature, shall I resume and code or I'm waiting?

**Comment by jponge** [comment]
Just go ahead :-)

**Comment by k33g** [comment]
@yloiseau @jponge code has 🛬 
Now, I need to add some tests

**Comment by k33g** [comment]
tests done 👋 @jponge

**Comment by k33g** [comment]
What I did:

```golo
  # cast a json string to a DynamicObject
  let obj1 = JSON.toDynamicObjectFromJSONString("""
    {
      "id":"bob",
      "remarks": null,
      "friends":[
        {"name":"sam"}, {"name":"jane"}, {"name":"john"}
      ],
      "address": {
        "street":"88 Colin P Kelly Jr St",
        "city":"San Francisco",
        "zip":"CA 94107",
        "country":"United States"
      }
    }
  """)

  println(obj1: friends(): get(2): name(): equals("john")) # true
  println(obj1: address(): city(): equals("San Francisco")) # true

  # cast a map to a DynamicObject
  let obj2 = JSON.toDynamicObjectFromMap(map[
    ["id", "bob"],
    ["friends", [
      map[["name", "sam"]],
      map[["name", "jane"]],
      map[["name", "john"]]
    ]],
    ["address", map[
      ["street", "88 Colin P Kelly Jr St"],
      ["city", "San Francisco"],
      ["zip", "CA 94107"],
      ["country", "United States"]
    ]]
  ])

  println(obj2: friends(): get(2): name(): equals("john")) # true
  println(obj2: address(): city(): equals("San Francisco")) # true

  # cast json string to a DynamicObjects list
  let objects1 = JSON.toDynamicObjectsListFromJSONString("""[
    {"message":"hello"},
    {
      "id":"bob",
      "friends":[
        {"name":"sam"}, {"name":"jane"}, {"name":"john"}
      ],
      "address": {
        "street":"88 Colin P Kelly Jr St",
        "city":"San Francisco",
        "zip":"CA 94107",
        "country":"United States"
      }
    }
  ]""")

  println(objects1: get(1): friends(): get(2): name(): equals("john")) # true
  println(objects1: get(1): address(): city(): equals("San Francisco")) # true

  # cast maps collection to a DynamicObjects list
  let objects2 = JSON.toDynamicObjectsListFromMapsCollection([
    map[["message", "hello"]],
    map[
      ["id", "bob"],
      ["friends", list[
        map[["name", "sam"]],
        map[["name", "jane"]],
        map[["name", "john"]]
      ]],
      ["address", map[
        ["street", "88 Colin P Kelly Jr St"],
        ["city", "San Francisco"],
        ["zip", "CA 94107"],
        ["country", "United States"]
      ]]
    ]
  ])

  println(objects2: get(1): friends(): get(2): name(): equals("john")) # true
  println(objects2: get(1): address(): city(): equals("San Francisco")) # true

```

**Comment by k33g** [comment]
It's strange the ip-validation was ok some hours ago ... 😤

**Comment by k33g** [comment]
Gardening my fork

**Pull request closed without merging**
