### PR TITLE
Python-like Contexts

### PR DESCRIPTION
**Pull request by yloiseau**
Contexts are an improved form of try-with-resource.

### CODE REVIEW

**Review by jponge — APPROVED** [review]
This is impressive work @yloiseau 👏  👏  👏

**Comment by k33g** [comment]
@yloiseau 🙏 can you please sync your feature branch with `master`, so I will be able to build it with GitPod to play with contexts

**Comment by yloiseau** [comment]
@k33g done!

**Review by k33g — APPROVED** [review]
build ✅

my test:

```golo
module my.context

import gololang.Control

function main = |args| {
  # enter: a closure executed when entering the context.
  # This closure takes no argument and return the value that will be bound to the context variable.
  let enter = -> {
    # do something
    println("👋 hey I'm the enter closure")
    return 42/0
  }

  # exit: a closure executed when exiting the context.
  # This closure has two parameters: the target (as returned by `enter`) and the exception raised by the wrapped block.
  let exit = |targetValueFromEnter, raisedException| {
    case {
      when raisedException is null {
        println("😃 all is ok 👏, the value is: " + targetValueFromEnter)
      }
      otherwise {
        println("😡 something wrong...")
        return raisedException
      }
    }
  }

  let myContext = context(enter, exit)

  &within(thing = myContext) {
    println("🤖 result is: " + thing)
    println("🤖 result is: " + thing())
  }

}

```
All good for me 👏  @yloiseau

**Pull request merged**
