### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by danielpetisme**
`fg_yellow` is a function...

### CODE REVIEW

**Comment by jponge** [comment]
Indeed, please go for a merge :-)

**Comment by danielpetisme** [comment]
Not sure ot have the appropriate permissions to merge it

**Comment by jponge** [comment]
@danielpetisme do you see the `merge` button?

**Comment by danielpetisme** [comment]
No captain

**Comment by jponge** [comment]
...but you are a developer per-Eclipse terms, right?

**Comment by danielpetisme** [comment]
I think so (paper done, account set up, access to the golo bugzilla and receive tons of eclipse mail....)

**Comment by jponge** [comment]
So then you need to open a bugzilla ticket to be granted rights on `eclipse/golo-lang`.

Meanwhile I'm merging this PR :smile:

**Comment by danielpetisme** [comment]
sound a familiar process...

**Pull request merged**
