### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by jponge**
I'm opening this pull-request to solicit feedback.

### CODE REVIEW

**Comment by jponge** [comment]
What would be left to do:

- [ ] Remove `pom.xml`
- [ ] Keep polishing the Gradle build file
- [ ] Edit the Travis-CI YAML file
- [ ] Extract the Maven plugin as a separate project?

**Comment by jponge** [comment]
Also see https://dev.eclipse.org/mhonarc/lists/golo-dev/maillist.html

**Comment by danielpetisme** [comment]
Impressive!
I'm not a Gradle expert so if I'm right now we have to run 
`./gradlew clean installDist` to build the distribution archive ?

We'll keep the rake file ?

**Comment by jponge** [comment]
./gradlew assemble

Because Gradle allows you to make your own tasks, we wouldn't need Rake
anymore.

**Comment by danielpetisme** [comment]
all the files are required? I mean we have:
* the folder `gradle/wrapper/` to configure the gradlew script
* `settings.gradle` which has one line....
* the OS-dependant `gradlew` scripts

Is me or it's 6 files to do our automation,instead of `pom.xml` and `Rakefile`

**Comment by jponge** [comment]
You could get rid of the wrapper, but it's idiomatic to have it (and forget it's here).

**Comment by jponge** [comment]
I've added tasks to compile and deploy the Maven plugin.

**Comment by jponge** [comment]
A vote conducted on `golo-dev` validates the switch to Gradle. I'll merge this branch soon and deal with the Eclipse Hudson server configurations to ensure that we continue publishing artifacts.

Thanks @jnizet @oehme for your contributions, you are our first 2 contributors since joining Eclipse :smiley:

**Pull request merged**
