### PR TITLE
Initial draft for a JOSS submission

### PR DESCRIPTION
**Pull request by jponge**
The intent is to submit Eclipse Golo to the Journal of Open Source Software (http://joss.theoj.org/).

I started with only a list of academic contributors to Eclipse Golo since they are likely to be the ones interesting in having Golo in JOSS.

All other contributors can still ask to be included / my intent is to do the submission on Thursday 29th September 2016.

### CODE REVIEW

**Comment by k33g** [comment]
@jponge if it's relevant, I really would like to be included 🙏 ❤️

**Comment by jponge** [comment]
@k33g sure, you're in.

**Comment by jponge** [comment]
@k33g Please check the data / affiliation

**Comment by Artpej** [comment]
It could be a great opportunity for me too, may i be included too?  :wink:

**Comment by jponge** [comment]
Ok everyone, just put the name / affiliation in comments and I'll add you 😄

**Comment by jponge** [comment]
@Artpej just give me your affiliation

**Comment by danielpetisme** [comment]
Me too, me too !

name: Daniel Petisme
affiliation: Manufacture Française des Pneumatiques Michelin

**Comment by Artpej** [comment]
@jponge you can set `almerys` as affiliation. many thanks

**Comment by willdurand** [comment]
Great initiative!

**Comment by jponge** [comment]
@franckverrot you broke the IP validation, perhaps you haven't used your Eclipse-registered email, and/or you haven't signed-off your commit.

**Comment by franckverrot** [comment]
@jponge haven't signed off indeed, but I've been using the same Eclipse-registered email :-(

**Comment by jponge** [comment]
@franckverrot I've rewritten and signed-off the commit.

**Comment by jponge** [comment]
Looks like we're good to go!

**Pull request merged**
