### PR TITLE
Integrate EditorConfig

### PR DESCRIPTION
**Pull request by danielpetisme**
I made it straightforward, indentation == 2 spaces.
If you want customize the config for a particular file type, just let me know.

### CODE REVIEW

**Comment by jponge** [comment]
Looks good to me. Could you do that PR on `versions/3.1` instead of `master`?

**Comment by yloiseau** [comment]
also good to me

**Comment by danielpetisme** [comment]
Ok so I'll close this PR and create a new one with the appropriate base.

**Comment by k33g** [comment]
oh oh @Daniel you have made a "philippade" with git ;)

**Comment by danielpetisme** [comment]
@k33g BTW, I just discovered
http://issue2pr.herokuapp.com/

**Comment by k33g** [comment]
:)

**Pull request closed without merging**
