### PR TITLE
Improve golodoc

### PR DESCRIPTION
**Pull request by yloiseau**
- markdown titles can be added into the documentations
- add highlight.js
- tweak the CSS
- change the way internal links are computed
- update the doc of gololang modules

### CODE REVIEW

**Comment by jponge** [comment]
Oh, the build failed! 😉

**Comment by jponge** [comment]
Other than that it looks good.

**Comment by jponge** [comment]
👍

**Comment by yloiseau** [comment]
Any remarks or other improvements?

**Comment by jponge** [comment]
For me it’s all very good.

**Pull request merged**
