### PR TITLE
Fix for #367

### PR DESCRIPTION
**Pull request by jponge**
Process the Gradle and Maven templates to have the Golo version edited.

### CODE REVIEW

**Comment by jponge** [comment]
Ping @danielpetisme re: #367

**Comment by danielpetisme** [comment]
How can we test automatically such thing?
Otherwise I'll do a manual test tonight.

**Comment by jponge** [comment]
> How can we test automatically such thing?
> Otherwise I'll do a manual test tonight.

`cat build/resources/…` :-)

Otherwise automated testing for that is about opening the resource, and playing with regexps.

**Comment by danielpetisme** [comment]
Tested, it works.

Regarding automation, is tricky to grep from a Java test the `build.gradle` version...

**Pull request merged**
