### PR TITLE
Change the golodoc html title

### PR DESCRIPTION
**Pull request by yloiseau**
When a lot of tabs are opened, the title was shortened as "Documentation
of..."
The module name is moved at the beginning such that it is displayed
even when shortened.

### CODE REVIEW

**Comment by Artpej** [comment]
:+1: , add a favicon is somthing else that could be very helpful too :wink: 

We could use a "`data:image/x-icon;base64...`"  in the link source to keep the documentation avaiability offline.

just ping, if you want me to amend this PR with this.

**Comment by yloiseau** [comment]
I put an hard coded String in the HTML template, but I wonder if it wouldn't be better to put a resource file and generate the base64 on the fly...

**Comment by yloiseau** [comment]
Does anyone know how to customize the asciidoctor template to also bundle a icon in the golo guide as suggested by @Artpej ?

**Comment by yloiseau** [comment]
Are we OK with this one ?

**Comment by jponge** [comment]
Yes!

**Pull request merged**
