### PR TITLE
Localization of error messages and command line options

### PR DESCRIPTION
**Pull request by yloiseau**
I started to localize as much as I can. Not finished yet. 

I'm not sure if we should localize runtime exception messages (e.g. when resolving a function).

Maybe I'm doing it wrong, feel free to comment.

### CODE REVIEW

**Comment by jponge** [comment]
Do you fallback on missing keys?

It often happens that with localisation translations fall behind the primary language.

**Comment by yloiseau** [comment]
If the defined locale does not have a corresponding translation resource, or if the key is not defined in the translation resource, the english message is used if it's what you mean

**Comment by yloiseau** [comment]
But I just noted that the colors in the output make syntastic (vim syntax checker) to fail. I need a way to turn it of, ether by checking if output is a TTY (if feasible) or at least with a command line flag

**Comment by yloiseau** [comment]
Are we OK with this one?

**Pull request merged**
