### PR TITLE
Starting a Gradle 6 Kotkin build script

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
@yloiseau I started this, it's not finished yet (docs, publishing) but it should already make tests pass.

**Comment by jponge** [comment]
@yloiseau I think right now the proposed build is more or less equivalent to the previous one, except that it's Gradle 6 and Kotlin script is a joy compared to Groovy. Feel free to test and let me know or directly push to this draft pr branch. There is still a few things to polish like building the Maven plugin.

I have configured the publication to Sonatype OSS, which we didn't have before. With my credentials set up I've been able to deploy a few 3.4.0-SNAPSHOT to https://oss.sonatype.org

This makes me think that:

1. there is no good incentive to go through Bintray as a gateway anymore, with OSS Sonatype credentials and a GnuPG key we can just publish directly releases and snapshots,
2. we used to publish binary builds (.zip / .tar.gz) on Bintray, but we could just upload to GitHub releases. It's only 2 files to upload.

WDYT?

/cc @k33g

**Comment by jponge** [comment]
Another side note: we could ditch Travis-CI and go with GitHub Actions for regular CI and deploying snapshots.

**Comment by jponge** [comment]
@yloiseau @k33g in terms of build functionality, do you see anything missing right now? There's still the `old.build.gradle` for reference in this draft.

**Comment by yloiseau** [comment]
```
$ ./gradlew publishToMavenLocal

Execution failed for task ':signMainPublication'.
> Cannot perform signing task ':signMainPublication' because it has no configured signatory
```

which used to work

**Comment by yloiseau** [comment]
The javadoc used to have a customized header for style sheet and highlighting JS

**Comment by jponge** [comment]
@yloiseau yes I haven't been able to port that

**Comment by jponge** [comment]
> ```
> $ ./gradlew publishToMavenLocal
> 
> Execution failed for task ':signMainPublication'.
> > Cannot perform signing task ':signMainPublication' because it has no configured signatory
> ```
> 
> 
> which used to work

That requires GPG/Gradle configuration on your side

**Comment by yloiseau** [comment]
> > ```
> > $ ./gradlew publishToMavenLocal
> > 
> > Execution failed for task ':signMainPublication'.
> > > Cannot perform signing task ':signMainPublication' because it has no configured signatory
> > ```
> > 
> > 
> > which used to work
> 
> That requires GPG/Gradle configuration on your side

Even for local repository ? It used to work (for local tests)

**Comment by jponge** [comment]
Check https://docs.gradle.org/current/userguide/signing_plugin.html

**Review by yloiseau — APPROVED** [review]

**Comment by jponge** [comment]
Still have to remove the old Gradle build file :-)

**Pull request merged**
