### PR TITLE
Use ModuleDocumentation in maven plugin

### PR DESCRIPTION
**Pull request by yloiseau**
Quick fix for #502 . Still no tests for the maven plugin :smile:

### CODE REVIEW

**Comment by k33g** [comment]
@yloiseau I'm not sure to understand what you fixed. 
the `pom.xml` generation when creating the golo project ?

**Comment by yloiseau** [comment]
@k33g the golo version in the `pom.xml` generated by `golo new` use the version of the golo command used to generate it (e.g. if you `golo new` in the dev branch, the golo version in the pom will currently be `3.3.0-SNAPSHOT`). The same version is used for the golo-maven-plugin, since they should match.
However, a bug in the golo-maven-plugin prevented it to be built/deployed on jcenter for the 3.2.0 version. Therefore, in jcenter, golo has version 3.2.0 (https://bintray.com/golo-lang/golo-lang/golo) and golo-maven-plugin has version 3.2.0-M6
(https://bintray.com/golo-lang/golo-lang/golo-maven-plugin), which prevents the use of golo 3.2.0 with maven. 
This is a fix for the golo-maven-plugin, that will permit to build golo-maven-plugin > 3.2.0-M6 and put it in sync with golo itself.

**Comment by k33g** [comment]
@yloiseau thx for the details, it's crystal clear

**Comment by yloiseau** [comment]
@jponge should we backport into a 3.2.1 release, or just wait for the 3.3.0-M1?

**Comment by jponge** [comment]
We could cherrypick this and other bugfixes into a 3.2 branch.

**Pull request merged**
